"""remove hora_fin, make user_id and fields optional

Revision ID: 5e6cf4e24f2e
Revises: 46a96c6fb82e
Create Date: 2026-08-05 00:35:51.194445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e6cf4e24f2e'
down_revision: Union[str, None] = '46a96c6fb82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'hora_fin')
    op.alter_column('patients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('appointments', sa.Column('hora_fin', postgresql.TIME(), autoincrement=False, nullable=False))
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
