"""unificar nombre_completo en patients y agregar obra_social_id a appointments

Revision ID: d88e226c00f6
Revises: 5e6cf4e24f2e
Create Date: 2026-08-05 01:55:56.691211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88e226c00f6'
down_revision: Union[str, None] = '5e6cf4e24f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('obra_social_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_appointments_obra_social_id'), 'appointments', ['obra_social_id'], unique=False)
    op.create_foreign_key('fk_appointments_obra_social_id', 'appointments', 'obras_sociales', ['obra_social_id'], ['id'])
    op.add_column('patients', sa.Column('nombre_completo', sa.String(length=200), nullable=True))
    op.execute(sa.text("UPDATE patients SET nombre_completo = trim(nombre || ' ' || apellido)"))
    op.alter_column('patients', 'nombre_completo', existing_type=sa.String(length=200), nullable=False)
    op.drop_column('patients', 'nombre')
    op.drop_column('patients', 'apellido')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.execute(
        sa.text(
            "UPDATE patients SET "
            "nombre = split_part(nombre_completo, ' ', 1), "
            "apellido = CASE WHEN strpos(nombre_completo, ' ') = 0 THEN '' "
            "ELSE trim(substr(nombre_completo, strpos(nombre_completo, ' ') + 1)) END"
        )
    )
    op.alter_column('patients', 'nombre', existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column('patients', 'apellido', existing_type=sa.VARCHAR(length=100), nullable=False)
    op.drop_column('patients', 'nombre_completo')
    op.drop_constraint('fk_appointments_obra_social_id', 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_obra_social_id'), table_name='appointments')
    op.drop_column('appointments', 'obra_social_id')
    # ### end Alembic commands ###
