"""agregar consultorio y nombre_normalizado a patients

Revision ID: f3a7b9c1d2e4
Revises: d88e226c00f6
Create Date: 2026-08-13 10:00:00.000000

"""
from __future__ import annotations

import unicodedata
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a7b9c1d2e4'
down_revision: Union[str, None] = 'd88e226c00f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _normalize(nombre: str) -> str:
    """Espejo de app.utils.normalize.normalize_nombre para el backfill."""
    sin_tildes = unicodedata.normalize("NFD", nombre)
    sin_tildes = "".join(c for c in sin_tildes if unicodedata.category(c) != "Mn")
    tokens = [t for t in sin_tildes.lower().split() if t]
    return " ".join(sorted(tokens))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'patients',
        sa.Column('consultorio', sa.String(length=20), server_default='Neurovital', nullable=False),
    )
    op.add_column(
        'patients',
        sa.Column('nombre_normalizado', sa.String(length=200), nullable=True),
    )

    # Backfill del nombre normalizado para los pacientes ya cargados.
    connection = op.get_bind()
    rows = connection.execute(
        sa.text("SELECT id, nombre_completo FROM patients")
    ).fetchall()
    for patient_id, nombre_completo in rows:
        connection.execute(
            sa.text(
                "UPDATE patients SET nombre_normalizado = :norm WHERE id = :id"
            ),
            {"norm": _normalize(nombre_completo), "id": patient_id},
        )

    op.alter_column(
        'patients',
        'nombre_normalizado',
        existing_type=sa.String(length=200),
        nullable=False,
    )
    op.create_index(
        'ix_patients_consultorio_normalizado',
        'patients',
        ['consultorio', 'nombre_normalizado'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_consultorio_normalizado', table_name='patients')
    op.drop_column('patients', 'nombre_normalizado')
    op.drop_column('patients', 'consultorio')
    # ### end Alembic commands ###
